image: docker:latest


variables:
  DOCKER_DRIVER: overlay2
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - docker info
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_BUILD_TOKEN" "$CI_REGISTRY"
  - git submodule sync --recursive
  - git submodule update --init --recursive

testing:
  stage: deploy
  script:
    - docker build --build-arg TOOL_NODE_FLAGS="--max-old-space-size=2048" -t "$CI_REGISTRY_IMAGE:${CI_COMMIT_REF_SLUG}" .
  only:
    - branches
  except:
    - thalhalla

thalhalla:
  stage: deploy
  script:
    - docker build --build-arg TOOL_NODE_FLAGS="--max-old-space-size=2048" -t "$CI_REGISTRY_IMAGE:latest" .
    - docker push "$CI_REGISTRY_IMAGE:latest"
  only:
    - thalhalla
